PamLib = "/lib/x86_64-linux-gnu/libpam.so.0"

# net filter
NetIface = "enp0s3"
MaxFailedCount = 3
TimeUnit = 60
ReportPeriod = 30

# Weak password dictionary
BuildDictOnly = false
Users = [
    "root",
    "mysql",
]
